    <p><strong><?php echo $this->title;?></strong></p>      
    <form method="post" action="/index/update">
    <table>
    <tr>
    <td width="100"></td><td><input name="id" type="hidden" value="<?php echo $this->id;?>"></td>
    </tr>    
    <tr>
    <td width="100">First Name : </td><td><input name="FirstName" type="text" value="<?php echo $this->FirstName;?>"></td>
    </tr>
    <tr>
    <td width="100">Last Name : </td><td><input name="LastName" type="text" value="<?php echo $this->LastName;?>"></td>
    </tr>
    <tr>
    <?php
    $Hobby=$this->Hobby;
    $Hobby1=explode(',',$Hobby);     
    $Hobbies=array("Music","Sports","Movies","Reading");
    foreach($Hobbies as $Hobby)
    {
    	if(in_array($Hobby,$Hobby1))
    	{?>
    		<td><input name="Hobby[]" type="checkbox" value="<?php echo $Hobby ?>" Checked><?php echo $Hobby?></td>
    		<?php
              } else
              {?>
            <td><input name="Hobby[]" type="checkbox" value="<?php echo $Hobby ?>"><?php echo $Hobby?></td>
                     <?php }
	?>
	<?php } ?>
	<tr>
    <td><input type="submit" name="submit" value="Submit"></td>
    </tr>
    </table>
    </form>
